# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/avsej/code/libdcp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/avsej/code/libdcp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/avsej/code/libdcp/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/avsej/code/libdcp/CMakeFiles /home/avsej/code/libdcp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/avsej/code/libdcp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dcp

# Build rule for target.
dcp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dcp
.PHONY : dcp

# fast build rule for target.
dcp/fast:
	$(MAKE) -f CMakeFiles/dcp.dir/build.make CMakeFiles/dcp.dir/build
.PHONY : dcp/fast

#=============================================================================
# Target rules for targets named ldcpcore

# Build rule for target.
ldcpcore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ldcpcore
.PHONY : ldcpcore

# fast build rule for target.
ldcpcore/fast:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/build
.PHONY : ldcpcore/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named file_manifest

# Build rule for target.
file_manifest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 file_manifest
.PHONY : file_manifest

# fast build rule for target.
file_manifest/fast:
	$(MAKE) -f CMakeFiles/file_manifest.dir/build.make CMakeFiles/file_manifest.dir/build
.PHONY : file_manifest/fast

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) -f CMakeFiles/dist.dir/build.make CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named cbc-send

# Build rule for target.
cbc-send: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cbc-send
.PHONY : cbc-send

# fast build rule for target.
cbc-send/fast:
	$(MAKE) -f tools/CMakeFiles/cbc-send.dir/build.make tools/CMakeFiles/cbc-send.dir/build
.PHONY : cbc-send/fast

#=============================================================================
# Target rules for targets named cbc-recv

# Build rule for target.
cbc-recv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cbc-recv
.PHONY : cbc-recv

# fast build rule for target.
cbc-recv/fast:
	$(MAKE) -f tools/CMakeFiles/cbc-recv.dir/build.make tools/CMakeFiles/cbc-recv.dir/build
.PHONY : cbc-recv/fast

contrib/cJSON/cJSON.o: contrib/cJSON/cJSON.c.o

.PHONY : contrib/cJSON/cJSON.o

# target to build an object file
contrib/cJSON/cJSON.c.o:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/contrib/cJSON/cJSON.c.o
.PHONY : contrib/cJSON/cJSON.c.o

contrib/cJSON/cJSON.i: contrib/cJSON/cJSON.c.i

.PHONY : contrib/cJSON/cJSON.i

# target to preprocess a source file
contrib/cJSON/cJSON.c.i:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/contrib/cJSON/cJSON.c.i
.PHONY : contrib/cJSON/cJSON.c.i

contrib/cJSON/cJSON.s: contrib/cJSON/cJSON.c.s

.PHONY : contrib/cJSON/cJSON.s

# target to generate assembly for a file
contrib/cJSON/cJSON.c.s:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/contrib/cJSON/cJSON.c.s
.PHONY : contrib/cJSON/cJSON.c.s

src/channel.o: src/channel.c.o

.PHONY : src/channel.o

# target to build an object file
src/channel.c.o:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/channel.c.o
.PHONY : src/channel.c.o

src/channel.i: src/channel.c.i

.PHONY : src/channel.i

# target to preprocess a source file
src/channel.c.i:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/channel.c.i
.PHONY : src/channel.c.i

src/channel.s: src/channel.c.s

.PHONY : src/channel.s

# target to generate assembly for a file
src/channel.c.s:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/channel.c.s
.PHONY : src/channel.c.s

src/client.o: src/client.c.o

.PHONY : src/client.o

# target to build an object file
src/client.c.o:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/client.c.o
.PHONY : src/client.c.o

src/client.i: src/client.c.i

.PHONY : src/client.i

# target to preprocess a source file
src/client.c.i:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/client.c.i
.PHONY : src/client.c.i

src/client.s: src/client.c.s

.PHONY : src/client.s

# target to generate assembly for a file
src/client.c.s:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/client.c.s
.PHONY : src/client.c.s

src/gethrtime.o: src/gethrtime.c.o

.PHONY : src/gethrtime.o

# target to build an object file
src/gethrtime.c.o:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/gethrtime.c.o
.PHONY : src/gethrtime.c.o

src/gethrtime.i: src/gethrtime.c.i

.PHONY : src/gethrtime.i

# target to preprocess a source file
src/gethrtime.c.i:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/gethrtime.c.i
.PHONY : src/gethrtime.c.i

src/gethrtime.s: src/gethrtime.c.s

.PHONY : src/gethrtime.s

# target to generate assembly for a file
src/gethrtime.c.s:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/gethrtime.c.s
.PHONY : src/gethrtime.c.s

src/io.o: src/io.c.o

.PHONY : src/io.o

# target to build an object file
src/io.c.o:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/io.c.o
.PHONY : src/io.c.o

src/io.i: src/io.c.i

.PHONY : src/io.i

# target to preprocess a source file
src/io.c.i:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/io.c.i
.PHONY : src/io.c.i

src/io.s: src/io.c.s

.PHONY : src/io.s

# target to generate assembly for a file
src/io.c.s:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/io.c.s
.PHONY : src/io.c.s

src/logging.o: src/logging.c.o

.PHONY : src/logging.o

# target to build an object file
src/logging.c.o:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/logging.c.o
.PHONY : src/logging.c.o

src/logging.i: src/logging.c.i

.PHONY : src/logging.i

# target to preprocess a source file
src/logging.c.i:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/logging.c.i
.PHONY : src/logging.c.i

src/logging.s: src/logging.c.s

.PHONY : src/logging.s

# target to generate assembly for a file
src/logging.c.s:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/logging.c.s
.PHONY : src/logging.c.s

src/ringbuffer.o: src/ringbuffer.c.o

.PHONY : src/ringbuffer.o

# target to build an object file
src/ringbuffer.c.o:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/ringbuffer.c.o
.PHONY : src/ringbuffer.c.o

src/ringbuffer.i: src/ringbuffer.c.i

.PHONY : src/ringbuffer.i

# target to preprocess a source file
src/ringbuffer.c.i:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/ringbuffer.c.i
.PHONY : src/ringbuffer.c.i

src/ringbuffer.s: src/ringbuffer.c.s

.PHONY : src/ringbuffer.s

# target to generate assembly for a file
src/ringbuffer.c.s:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/ringbuffer.c.s
.PHONY : src/ringbuffer.c.s

src/session.o: src/session.c.o

.PHONY : src/session.o

# target to build an object file
src/session.c.o:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/session.c.o
.PHONY : src/session.c.o

src/session.i: src/session.c.i

.PHONY : src/session.i

# target to preprocess a source file
src/session.c.i:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/session.c.i
.PHONY : src/session.c.i

src/session.s: src/session.c.s

.PHONY : src/session.s

# target to generate assembly for a file
src/session.c.s:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/session.c.s
.PHONY : src/session.c.s

src/settings.o: src/settings.c.o

.PHONY : src/settings.o

# target to build an object file
src/settings.c.o:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/settings.c.o
.PHONY : src/settings.c.o

src/settings.i: src/settings.c.i

.PHONY : src/settings.i

# target to preprocess a source file
src/settings.c.i:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/settings.c.i
.PHONY : src/settings.c.i

src/settings.s: src/settings.c.s

.PHONY : src/settings.s

# target to generate assembly for a file
src/settings.c.s:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/settings.c.s
.PHONY : src/settings.c.s

src/topo.o: src/topo.c.o

.PHONY : src/topo.o

# target to build an object file
src/topo.c.o:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/topo.c.o
.PHONY : src/topo.c.o

src/topo.i: src/topo.c.i

.PHONY : src/topo.i

# target to preprocess a source file
src/topo.c.i:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/topo.c.i
.PHONY : src/topo.c.i

src/topo.s: src/topo.c.s

.PHONY : src/topo.s

# target to generate assembly for a file
src/topo.c.s:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/topo.c.s
.PHONY : src/topo.c.s

src/utilities.o: src/utilities.c.o

.PHONY : src/utilities.o

# target to build an object file
src/utilities.c.o:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/utilities.c.o
.PHONY : src/utilities.c.o

src/utilities.i: src/utilities.c.i

.PHONY : src/utilities.i

# target to preprocess a source file
src/utilities.c.i:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/utilities.c.i
.PHONY : src/utilities.c.i

src/utilities.s: src/utilities.c.s

.PHONY : src/utilities.s

# target to generate assembly for a file
src/utilities.c.s:
	$(MAKE) -f CMakeFiles/ldcpcore.dir/build.make CMakeFiles/ldcpcore.dir/src/utilities.c.s
.PHONY : src/utilities.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... package_source"
	@echo "... dcp"
	@echo "... package"
	@echo "... list_install_components"
	@echo "... ldcpcore"
	@echo "... uninstall"
	@echo "... install/strip"
	@echo "... file_manifest"
	@echo "... dist"
	@echo "... cbc-send"
	@echo "... cbc-recv"
	@echo "... contrib/cJSON/cJSON.o"
	@echo "... contrib/cJSON/cJSON.i"
	@echo "... contrib/cJSON/cJSON.s"
	@echo "... src/channel.o"
	@echo "... src/channel.i"
	@echo "... src/channel.s"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/gethrtime.o"
	@echo "... src/gethrtime.i"
	@echo "... src/gethrtime.s"
	@echo "... src/io.o"
	@echo "... src/io.i"
	@echo "... src/io.s"
	@echo "... src/logging.o"
	@echo "... src/logging.i"
	@echo "... src/logging.s"
	@echo "... src/ringbuffer.o"
	@echo "... src/ringbuffer.i"
	@echo "... src/ringbuffer.s"
	@echo "... src/session.o"
	@echo "... src/session.i"
	@echo "... src/session.s"
	@echo "... src/settings.o"
	@echo "... src/settings.i"
	@echo "... src/settings.s"
	@echo "... src/topo.o"
	@echo "... src/topo.i"
	@echo "... src/topo.s"
	@echo "... src/utilities.o"
	@echo "... src/utilities.i"
	@echo "... src/utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

